version: "3"
services:
  library:
    container_name: library
    image: slavarichkov/library
    ports:
      - "3000:3000"
  counter:
    container_name: counter
    image: slavarichkov/counter
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "3001:3001"